openapi: 3.0.0
info:
  title: Datti API
  description: 誰にいくら払ったっけ？を記録するサービス
  version: 0.0.0
tags:
  - name: Lendings
  - name: Borrowings
  - name: Credits
  - name: Health
paths:
  /borrowings:
    get:
      operationId: Borrowing_getAll
      summary: 全ての借り入れの取得
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Borrowing.GetAllResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Borrowings
  /credits:
    get:
      operationId: Credits_list
      summary: 債権一覧の取得
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Credit'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Credits
  /health:
    get:
      operationId: Health_check
      summary: ヘルスチェック
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health.CheckResponse'
      tags:
        - Health
  /lendings:
    post:
      operationId: Lending_create
      summary: 立て替えの作成
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lending.CreateResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Lendings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lending.CreateRequest'
  /lendings/{id}:
    get:
      operationId: Lending_get
      summary: 立て替えの取得
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lending.GetResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Lendings
    put:
      operationId: Lending_update
      summary: 立て替えの更新
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lending.UpdateResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Access is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Lendings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lending.UpdateRequest'
security:
  - BearerAuth: []
components:
  schemas:
    Borrowing.GetAllResponse:
      type: object
      required:
        - id
        - name
        - amount
        - eventDate
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        name:
          type: string
        amount:
          type: integer
          format: uint64
        eventDate:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Credit:
      type: object
      required:
        - userId
        - amount
      properties:
        userId:
          type: string
        amount:
          type: integer
          format: int64
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    Health.CheckResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum:
            - ok
        timestamp:
          type: string
          format: date-time
    Lending.CreateRequest:
      type: object
      required:
        - name
        - amount
        - eventDate
        - debts
      properties:
        name:
          type: string
        amount:
          type: integer
          format: uint64
        eventDate:
          type: string
          format: date-time
        debts:
          type: array
          items:
            $ref: '#/components/schemas/Lending.DebtParmam'
    Lending.CreateResponse:
      type: object
      required:
        - id
        - name
        - amount
        - eventDate
        - debts
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        name:
          type: string
        amount:
          type: integer
          format: uint64
        eventDate:
          type: string
          format: date-time
        debts:
          type: array
          items:
            $ref: '#/components/schemas/Lending.DebtParmam'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Lending.DebtParmam:
      type: object
      required:
        - userId
        - amount
      properties:
        userId:
          type: string
        amount:
          type: integer
          format: uint64
    Lending.GetResponse:
      type: object
      required:
        - id
        - name
        - amount
        - eventDate
        - debts
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        name:
          type: string
        amount:
          type: integer
          format: uint64
        eventDate:
          type: string
          format: date-time
        debts:
          type: array
          items:
            $ref: '#/components/schemas/Lending.DebtParmam'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Lending.UpdateRequest:
      type: object
      required:
        - name
        - amount
        - eventDate
        - debts
      properties:
        name:
          type: string
        amount:
          type: integer
          format: uint64
        eventDate:
          type: string
          format: date-time
        debts:
          type: array
          items:
            $ref: '#/components/schemas/Lending.DebtParmam'
    Lending.UpdateResponse:
      type: object
      required:
        - id
        - name
        - amount
        - eventDate
        - debts
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        name:
          type: string
        amount:
          type: integer
          format: uint64
        eventDate:
          type: string
          format: date-time
        debts:
          type: array
          items:
            $ref: '#/components/schemas/Lending.DebtParmam'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer
servers:
  - url: https://datti-api.haebeal.net
    description: 本番環境
    variables: {}
