version: '3'

services:
  postgres:
    container_name: datti_db
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: datti_db
      TZ: Asia/Tokyo
