name: Deploy OpenAPI

on:
  push:
    branches: [feature/**, develop, main]
    paths:
      - openapi/**
      - .github/workflows/deploy-swagger-ui.yml

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: openapi
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run compile

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: docs/swagger-ui
          spec-file: ./tsp-output/@typespec/openapi3/openapi.yaml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/swagger-ui
