name: Pipeline

on:
  push:
    branches: [feature/**, main]

jobs:
  # deploy-fly-feat:
  #   name: deploy fly to dev environment
  #   if: startsWith(github.ref, 'refs/heads/feature/')
  #   uses: ./.github/workflows/fly_deploy.yml
  #   permissions:
  #     id-token: write
  #     contents: read
  #   with:
  #     environment: dev
  #     ref: ${{ github.sha }}
  #   secrets: inherit
  deploy-fly-main:
    name: deploy fly to prod environment
    if: startsWith(github.ref, 'refs/heads/feature/')
    # if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
    uses: ./.github/workflows/fly_deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: prod
      ref: ${{ github.sha }}
    secrets: inherit
