name: Pipeline

on:
  push:
    branches: [feature/**, develop, release, main]

jobs:
  deploy-feat:
    name: deploy cloudrun to dev environment
    if: ${{ github.ref == 'refs/heads/feature/**' || github.base_ref == 'feature/**' }}
    uses: ./.github/workflows/_deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: dev
      ref: ${{ github.sha }}
    secrets: inherit
  deploy-dev:
    name: deploy cloudrun to reg environment
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: ./.github/workflows/_deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: reg
      ref: ${{ github.sha }}
    secrets: inherit